package client;

public class Combination extends javax.swing.JPanel {
    
    /** Creates new form Combination */
    public Combination() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        titleLabelCombination = new javax.swing.JLabel();
        startPageButtonCombination = new javax.swing.JButton();
        inventarPanelCombination = new javax.swing.JPanel();
        logoutButtonCombination = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 204));

        titleLabelCombination.setFont(new java.awt.Font("Tahoma", 1, 18));
        titleLabelCombination.setForeground(new java.awt.Color(255, 51, 0));
        titleLabelCombination.setText("Element's combination");

        startPageButtonCombination.setText("Start page");
        startPageButtonCombination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startPageButtonCombinationHandler(evt);
            }
        });

        inventarPanelCombination.setBackground(new java.awt.Color(255, 255, 204));

        javax.swing.GroupLayout inventarPanelCombinationLayout = new javax.swing.GroupLayout(inventarPanelCombination);
        inventarPanelCombination.setLayout(inventarPanelCombinationLayout);
        inventarPanelCombinationLayout.setHorizontalGroup(
            inventarPanelCombinationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 257, Short.MAX_VALUE)
        );
        inventarPanelCombinationLayout.setVerticalGroup(
            inventarPanelCombinationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 174, Short.MAX_VALUE)
        );

        logoutButtonCombination.setText("Logout");
        logoutButtonCombination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonCombinationHandler(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addComponent(titleLabelCombination)
                .addGap(95, 95, 95))
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(logoutButtonCombination, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(startPageButtonCombination, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inventarPanelCombination, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(titleLabelCombination)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(startPageButtonCombination)
                        .addGap(35, 35, 35)
                        .addComponent(logoutButtonCombination))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(inventarPanelCombination, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
    }// </editor-fold>                        

    private void startPageButtonCombinationHandler(java.awt.event.ActionEvent evt) {                                                   
        // TODO add your handling code here:
}                                                  

    private void logoutButtonCombinationHandler(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
    }                                               
    
    public javax.swing.JButton getStartPageButtonCombination() 
    {
		return startPageButtonCombination;
	}
    
    public javax.swing.JButton getLogoutButtonCombination() 
    {
		return logoutButtonCombination;
	}
    
    
    
    // Variables declaration - do not modify                     
    private javax.swing.JPanel inventarPanelCombination;
    private javax.swing.JButton logoutButtonCombination;
    private javax.swing.JButton startPageButtonCombination;
    private javax.swing.JLabel titleLabelCombination;
    // End of variables declaration                   
    
}
