
public class Sale extends javax.swing.JPanel {
    
    /** Creates new form Sale */
    public Sale() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        titleLabelSale = new javax.swing.JLabel();
        startPageButtonSale = new javax.swing.JButton();
        InventarPanelSale = new javax.swing.JPanel();
        logoutButtonSale = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 204));

        titleLabelSale.setFont(new java.awt.Font("Tahoma", 1, 18));
        titleLabelSale.setForeground(new java.awt.Color(255, 51, 0));
        titleLabelSale.setText("Saling elements");

        startPageButtonSale.setText("Start page");
        startPageButtonSale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startPageButtonSaleHandler(evt);
            }
        });

        InventarPanelSale.setBackground(new java.awt.Color(255, 255, 204));

        javax.swing.GroupLayout InventarPanelSaleLayout = new javax.swing.GroupLayout(InventarPanelSale);
        InventarPanelSale.setLayout(InventarPanelSaleLayout);
        InventarPanelSaleLayout.setHorizontalGroup(
            InventarPanelSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 254, Short.MAX_VALUE)
        );
        InventarPanelSaleLayout.setVerticalGroup(
            InventarPanelSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 166, Short.MAX_VALUE)
        );

        logoutButtonSale.setText("Logout");
        logoutButtonSale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonSaleHandler(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(titleLabelSale))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(logoutButtonSale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(startPageButtonSale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(InventarPanelSale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(titleLabelSale)
                        .addGap(32, 32, 32)
                        .addComponent(InventarPanelSale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(startPageButtonSale)
                        .addGap(34, 34, 34)
                        .addComponent(logoutButtonSale)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
    }// </editor-fold>

    private void startPageButtonSaleHandler(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void logoutButtonSaleHandler(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        
    
    public javax.swing.JButton getLogoutButtonSale() 
    {
		return logoutButtonSale;
	}
    
    public javax.swing.JButton getStartPageButtonSale() 
    {
		return startPageButtonSale;
	}
    
    // Variables declaration - do not modify
    private javax.swing.JPanel InventarPanelSale;
    private javax.swing.JButton logoutButtonSale;
    private javax.swing.JButton startPageButtonSale;
    private javax.swing.JLabel titleLabelSale;
    // End of variables declaration
    
}
    
