import java.awt.Color;

import javax.swing.JPanel;
import javax.swing.JScrollPane;


public class StartPage extends javax.swing.JPanel {
    
    /** Creates new form StartPage */
    public StartPage(String[] header,String[][] values) {
    	
        initComponents(header,values);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents(String[] header,String[][] values) {

        titleLabelStartPage = new javax.swing.JLabel();
        logoutButtonStartPage = new javax.swing.JButton();
        combinationButtonStartPage = new javax.swing.JButton();
        buyButtonStarPage = new javax.swing.JButton();
        saleButtonStartPage = new javax.swing.JButton();
        panelStartPage = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        nrPuncteLabelStartPage = new javax.swing.JLabel();
        puncteLabelStartPage = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 204));

        titleLabelStartPage.setFont(new java.awt.Font("Tahoma", 1, 18));
        titleLabelStartPage.setForeground(new java.awt.Color(255, 51, 0));
        titleLabelStartPage.setText("Welcome to Atlantida");

        logoutButtonStartPage.setText("Logout");
        logoutButtonStartPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonStartPageHandler(evt);
            }
        });

        combinationButtonStartPage.setText("Combination");
        combinationButtonStartPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combinationButtonStartPageHandler(evt);
            }
        });

        buyButtonStarPage.setText("Buy");
        buyButtonStarPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyButtonStartPageHandler(evt);
            }
        });

        saleButtonStartPage.setText("Sale");
        saleButtonStartPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saleButtonStartPageHandler(evt);
            }
        });

        panelStartPage.setBackground(new java.awt.Color(255, 255, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel1.setForeground(new java.awt.Color(255, 51, 0));
        jLabel1.setText("Plan stock");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setAutoscrolls(true);
        

        
        jTable1.setAutoCreateRowSorter(true);
        if (header!=null && values != null)
        {
	        jTable1.setModel(new javax.swing.table.DefaultTableModel(
	                values, header));
	        jTable1.setCellSelectionEnabled(false);
	        jTable1.setRowSelectionAllowed(true);
	        jTable1.removeColumn(jTable1.getColumn("ID"));
	        jTable1.removeColumn(jTable1.getColumn("PARINTE"));
	        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
	        jScrollPane1.setViewportView(jTable1);
	      
        }
        javax.swing.GroupLayout panelStartPageLayout = new javax.swing.GroupLayout(panelStartPage);
        panelStartPage.setLayout(panelStartPageLayout);
        panelStartPageLayout.setHorizontalGroup(
        	panelStartPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStartPageLayout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(jLabel1)
                .addContainerGap(125, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelStartPageLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                .addGap(32, 32, 32))
        );
        panelStartPageLayout.setVerticalGroup(
            panelStartPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStartPageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                .addGap(61, 61, 61))
        );

        nrPuncteLabelStartPage.setFont(new java.awt.Font("Georgia", 1, 14));
        nrPuncteLabelStartPage.setForeground(new java.awt.Color(255, 51, 0));
        nrPuncteLabelStartPage.setText("Numarul de puncte:");

        puncteLabelStartPage.setFont(new java.awt.Font("Georgia", 1, 14));
        puncteLabelStartPage.setForeground(new java.awt.Color(255, 51, 0));
        puncteLabelStartPage.setText("4230");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(logoutButtonStartPage, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(saleButtonStartPage, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(buyButtonStarPage, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(combinationButtonStartPage, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelStartPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(titleLabelStartPage))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(nrPuncteLabelStartPage)
                        .addGap(18, 18, 18)
                        .addComponent(puncteLabelStartPage, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(titleLabelStartPage)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(logoutButtonStartPage)
                        .addGap(4, 4, 4)
                        .addComponent(saleButtonStartPage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buyButtonStarPage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combinationButtonStartPage)
                        .addGap(119, 119, 119))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(panelStartPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nrPuncteLabelStartPage)
                    .addComponent(puncteLabelStartPage))
                .addContainerGap())
        );
    }// </editor-fold>

  
 
    private void logoutButtonStartPageHandler(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void combinationButtonStartPageHandler(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void buyButtonStartPageHandler(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void saleButtonStartPageHandler(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }
    
    public javax.swing.JButton getLogoutButtonStartPage() 
    {
		return logoutButtonStartPage;
	}
    
    public javax.swing.JButton getCombinationButtonStartPage() 
    {
		return combinationButtonStartPage;
	}
    
    public javax.swing.JButton getBuyButtonStartPage() 
    {
		return buyButtonStarPage;
	}
    
    public javax.swing.JButton getSaleButtonStartPage() 
    {
		return saleButtonStartPage;
	}
    
    public void setPanelStartPage(javax.swing.JPanel panelStartPage) 
    {
    	this.panelStartPage = panelStartPage;
    }
    
    public javax.swing.JPanel getPanelStartPage() {
		return panelStartPage;
	}
    
    public javax.swing.JLabel getPuncteLabelStartPage() {
		return puncteLabelStartPage;
	}

    public javax.swing.JTable getJTable1() {
		return jTable1;
	}
    
    // Variables declaration - do not modify
    private javax.swing.JButton buyButtonStarPage;
    private javax.swing.JButton combinationButtonStartPage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton logoutButtonStartPage;
    private javax.swing.JLabel nrPuncteLabelStartPage;
    private javax.swing.JPanel panelStartPage;
    private javax.swing.JLabel puncteLabelStartPage;
    private javax.swing.JButton saleButtonStartPage;
    private javax.swing.JLabel titleLabelStartPage;
    // End of variables declaration
    
}




