package administrator;

public class Admin extends javax.swing.JPanel {
    
    /** Creates new form Admin */
    public Admin() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label1Admin = new javax.swing.JLabel();
        label2Admin = new javax.swing.JLabel();
        label3Admin = new javax.swing.JLabel();
        labe4Admin = new javax.swing.JLabel();
        label5Admin = new javax.swing.JLabel();
        label6Admin = new javax.swing.JLabel();
        label7Admin = new javax.swing.JLabel();
        label8Admin = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        label10Admin = new javax.swing.JLabel();
        label11Admin = new javax.swing.JLabel();
        label12Admin = new javax.swing.JLabel();
        trimiteDateButtonAdmin = new javax.swing.JButton();
        textField10Admin = new javax.swing.JTextField();
        textField3Admin = new javax.swing.JTextField();
        textField2Admin = new javax.swing.JTextField();
        textField1Admin = new javax.swing.JTextField();
        textField7Admin = new javax.swing.JTextField();
        textField8Admin = new javax.swing.JTextField();
        textField9Admin = new javax.swing.JTextField();
        logoutButtonAdmin = new javax.swing.JButton();
        label13Admin = new javax.swing.JLabel();
        textField4Admin = new javax.swing.JTextField();
        textField5Admin = new javax.swing.JTextField();
        textField6Admin = new javax.swing.JTextField();
        formulaButtonAdmin = new javax.swing.JButton();
        label14Admin = new javax.swing.JLabel();
        label15Admin = new javax.swing.JLabel();
        numeElementLabelAdmin = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 204));

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        label1Admin.setFont(new java.awt.Font("Georgia", 1, 12));
        label1Admin.setForeground(new java.awt.Color(255, 51, 0));
        label1Admin.setText("Durata unui ciclu");

        label2Admin.setFont(new java.awt.Font("Georgia", 1, 12));
        label2Admin.setForeground(new java.awt.Color(255, 51, 0));
        label2Admin.setText("Nr. initial de puncte");

        label3Admin.setFont(new java.awt.Font("Georgia", 1, 12));
        label3Admin.setForeground(new java.awt.Color(255, 51, 0));
        label3Admin.setText("Val. max. pt elem. atomice");

        labe4Admin.setFont(new java.awt.Font("Georgia", 1, 14));
        labe4Admin.setForeground(new java.awt.Color(255, 51, 0));
        labe4Admin.setText("Nr de puncte cu care:");

        label5Admin.setFont(new java.awt.Font("Georgia", 1, 12));
        label5Admin.setForeground(new java.awt.Color(255, 51, 0));
        label5Admin.setText("- scade sanatatea");

        label6Admin.setFont(new java.awt.Font("Georgia", 1, 12));
        label6Admin.setForeground(new java.awt.Color(255, 51, 0));
        label6Admin.setText("- scade randamentul");

        label7Admin.setFont(new java.awt.Font("Georgia", 1, 12));
        label7Admin.setForeground(new java.awt.Color(255, 51, 0));
        label7Admin.setText("- creste consumul");

        label8Admin.setFont(new java.awt.Font("Georgia", 1, 12));
        label8Admin.setForeground(new java.awt.Color(255, 51, 0));
        label8Admin.setText("Adaugare propr. speciala");

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 12));
        jLabel1.setForeground(new java.awt.Color(255, 51, 0));
        jLabel1.setText("Durata in timp a licitatiei:");

        label10Admin.setFont(new java.awt.Font("Georgia", 1, 12));
        label10Admin.setForeground(new java.awt.Color(255, 51, 0));
        label10Admin.setText("- fara alti jucatori");

        label11Admin.setFont(new java.awt.Font("Georgia", 1, 12));
        label11Admin.setForeground(new java.awt.Color(255, 51, 0));
        label11Admin.setText("- cu alti jucatori");

        label12Admin.setFont(new java.awt.Font("Georgia", 1, 12));
        label12Admin.setForeground(new java.awt.Color(255, 51, 0));
        label12Admin.setText("Pret");

        trimiteDateButtonAdmin.setText("Trimite date");
        trimiteDateButtonAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trimiteDateButtonAdminHandler(evt);
            }
        });

        textField10Admin.setText("");

        textField3Admin.setText("jTextField3");
        textField3Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField3AdminActionPerformed(evt);
            }
        });

        textField2Admin.setText("jTextField2");

        textField1Admin.setText("jTextField1");

        textField8Admin.setText("jTextField8");

        textField9Admin.setText("");

        logoutButtonAdmin.setText("Logout");
        logoutButtonAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonAdminHandler(evt);
            }
        });

        label13Admin.setFont(new java.awt.Font("Georgia", 1, 12));
        label13Admin.setForeground(new java.awt.Color(255, 51, 0));
        label13Admin.setText("minute");

        textField4Admin.setText("jTextField4");

        textField5Admin.setText("jTextField5");

        textField6Admin.setText("jTextField6");

        formulaButtonAdmin.setText("Formula");
        formulaButtonAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formulaButtonAdminHandler(evt);
            }
        });

        label14Admin.setFont(new java.awt.Font("Georgia", 1, 12));
        label14Admin.setForeground(new java.awt.Color(255, 51, 0));
        label14Admin.setText("sec");

        label15Admin.setFont(new java.awt.Font("Georgia", 1, 12));
        label15Admin.setForeground(new java.awt.Color(255, 51, 0));
        label15Admin.setText("sec");

        numeElementLabelAdmin.setFont(new java.awt.Font("Georgia", 1, 12));
        numeElementLabelAdmin.setForeground(new java.awt.Color(255, 51, 0));
        numeElementLabelAdmin.setText("Nume element");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(numeElementLabelAdmin)
                .addContainerGap(415, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(116, 116, 116)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label6Admin)
                                    .addComponent(label5Admin)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(label10Admin)
                                            .addComponent(label11Admin))
                                        .addComponent(label7Admin))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labe4Admin))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label1Admin)
                                    .addComponent(label2Admin)
                                    .addComponent(jLabel1))
                                .addGap(94, 94, 94)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(textField10Admin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textField9Admin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textField7Admin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textField8Admin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textField6Admin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textField2Admin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textField1Admin, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textField3Admin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textField4Admin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textField5Admin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(label15Admin)
                                        .addComponent(label14Admin))
                                    .addComponent(label13Admin)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(trimiteDateButtonAdmin)
                                    .addGap(197, 197, 197))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(label8Admin)
                                    .addGap(229, 229, 229)))
                            .addComponent(label12Admin)
                            .addComponent(label3Admin))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(logoutButtonAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(formulaButtonAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(label1Admin)
                        .addGap(13, 13, 13)
                        .addComponent(label2Admin))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label13Admin)
                            .addComponent(textField1Admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textField2Admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(textField3Admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textField4Admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textField5Admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labe4Admin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(label5Admin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label6Admin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label7Admin)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(label10Admin)
                                .addGap(9, 9, 9)
                                .addComponent(label11Admin))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(textField6Admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textField8Admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(label15Admin)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label14Admin)
                        .addGap(32, 32, 32)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numeElementLabelAdmin)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label8Admin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label3Admin, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label12Admin)
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(trimiteDateButtonAdmin)
                            .addComponent(logoutButtonAdmin)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textField7Admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(formulaButtonAdmin))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textField9Admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textField10Admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29))
        );

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 14));
        jLabel2.setForeground(new java.awt.Color(255, 51, 0));
        jLabel2.setText("Administrator");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(jLabel2))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
    }// </editor-fold>

    private void formulaButtonAdminHandler(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void trimiteDateButtonAdminHandler(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void logoutButtonAdminHandler(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void textField3AdminActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }
    public javax.swing.JButton getLogoutButtonAdmin() {
		return logoutButtonAdmin;
	}
    public javax.swing.JButton getTrimiteDateButtonAdmin() {
		return trimiteDateButtonAdmin;
	}
    public javax.swing.JButton getFormulaButtonAdmin() {
		return formulaButtonAdmin;
	}
    
    public javax.swing.JTextField getTextField7Admin() {
		return textField7Admin;
	}
    public javax.swing.JTextField getTextField9Admin() {
		return textField9Admin;
	}
    public javax.swing.JTextField getTextField10Admin() {
		return textField10Admin;
	}
    public javax.swing.JTextField getJTextField1() {
    	return jTextField1;
    }
    // Variables declaration - do not modify
    private javax.swing.JButton formulaButtonAdmin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField textField10Admin;
    private javax.swing.JLabel labe4Admin;
    private javax.swing.JLabel label10Admin;
    private javax.swing.JLabel label11Admin;
    private javax.swing.JLabel label12Admin;
    private javax.swing.JLabel label13Admin;
    private javax.swing.JLabel label14Admin;
    private javax.swing.JLabel label15Admin;
    private javax.swing.JLabel label1Admin;
    private javax.swing.JLabel label2Admin;
    private javax.swing.JLabel label3Admin;
    private javax.swing.JLabel label5Admin;
    private javax.swing.JLabel label6Admin;
    private javax.swing.JLabel label7Admin;
    private javax.swing.JLabel label8Admin;
    private javax.swing.JButton logoutButtonAdmin;
    private javax.swing.JLabel numeElementLabelAdmin;
    public javax.swing.JTextField textField1Admin;
    public javax.swing.JTextField textField2Admin;
    public javax.swing.JTextField textField3Admin;
    public javax.swing.JTextField textField4Admin;
    public javax.swing.JTextField textField5Admin;
    public javax.swing.JTextField textField6Admin;
    private javax.swing.JTextField textField7Admin;
    public javax.swing.JTextField textField8Admin;
    private javax.swing.JTextField textField9Admin;
    private javax.swing.JButton trimiteDateButtonAdmin;
    // End of variables declaration
    
}


  
    
 