package administrator;

import javax.swing.JOptionPane;
import javax.swing.JOptionPane;


public class LoginAdmin extends javax.swing.JPanel {
    
    /** Creates new form Login */
    public LoginAdmin() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */

    private void initComponents() {

        loginLabelLogin = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        usernameLabelLogin = new javax.swing.JLabel();
        passwordLabelLogin = new javax.swing.JLabel();
        loginButtonLogin = new javax.swing.JButton();
        usernameTextFieldLogin = new javax.swing.JTextField();
        passwordPasswordFieldLogin = new javax.swing.JPasswordField();
        rulesButtonLogin = new javax.swing.JButton();
        creditsButtonLogin = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 204));

        loginLabelLogin.setFont(new java.awt.Font("Tahoma", 1, 18));
        loginLabelLogin.setForeground(new java.awt.Color(255, 51, 0));
        loginLabelLogin.setText("Login");

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        usernameLabelLogin.setText("Username");

        passwordLabelLogin.setText("Password");

        loginButtonLogin.setText("Login");
        loginButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonLoginHandler(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usernameLabelLogin)
                            .addComponent(passwordLabelLogin))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(passwordPasswordFieldLogin)
                            .addComponent(usernameTextFieldLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(loginButtonLogin)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameLabelLogin)
                    .addComponent(usernameTextFieldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(passwordLabelLogin)
                    .addComponent(passwordPasswordFieldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(loginButtonLogin)
                .addGap(33, 33, 33))
        );

  
        rulesButtonLogin.setText("Rules");
        rulesButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rulesButtonLoginHandler(evt);
            }
        });

        creditsButtonLogin.setText("Credits");
        creditsButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditsButtonLoginHandler(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                     .addComponent(rulesButtonLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(creditsButtonLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(42, 42, 42))
            .addGroup(layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(loginLabelLogin)
                .addContainerGap(177, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(loginLabelLogin)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(rulesButtonLogin)
                        .addGap(26, 26, 26)
                        .addComponent(creditsButtonLogin)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap(23, Short.MAX_VALUE))))
        );
    }

    private void loginButtonLoginHandler(java.awt.event.ActionEvent evt) 
    {  
     	String name = usernameTextFieldLogin.getText();
		String pwd = new String(passwordPasswordFieldLogin.getPassword());
		
		if(!name.equals("laura") || !pwd.equals("laura")) 
		{
		    JOptionPane.showMessageDialog(this, "Incorrect username/password combination.", "Login Error", JOptionPane.ERROR_MESSAGE);
		}
    }

    private void registerButtonLogin(java.awt.event.ActionEvent evt) 
    {
    	
    }

    private void rulesButtonLoginHandler(java.awt.event.ActionEvent evt) 
    {
       
    }

    private void creditsButtonLoginHandler(java.awt.event.ActionEvent evt) 
    {
        
    }
    
    public javax.swing.JButton getLoginButtonLogin() 
    {
		return loginButtonLogin;
	}
    
    
    public javax.swing.JTextField getUsernameTextFieldLogin() {
		return usernameTextFieldLogin;
	}
    
    public javax.swing.JPasswordField getPasswordPasswordFieldLogin() {
		return passwordPasswordFieldLogin;
	}
    
    public javax.swing.JButton getRulesButtonLogin() 
    {
		return rulesButtonLogin;
	}
    public javax.swing.JButton getCreditsButtonLogin() 
    {
		return creditsButtonLogin;
	}
    
    private javax.swing.JButton creditsButtonLogin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginButtonLogin;
    private javax.swing.JLabel loginLabelLogin;
    private javax.swing.JLabel passwordLabelLogin;
    private javax.swing.JPasswordField passwordPasswordFieldLogin;
    private javax.swing.JButton rulesButtonLogin;
    private javax.swing.JLabel usernameLabelLogin;
    private javax.swing.JTextField usernameTextFieldLogin;
    
}